stages:
    -   test

test-py36:
    image: python:3.6
    script:
        -   apt update
        -   apt install --yes --no-install-recommends gcc portaudio19-dev
        -   python3.6 -m venv venv
        -   venv/bin/python -m pip install --upgrade tox wheel pip
        -   venv/bin/python -m tox -e py36
    stage: test

test-py37:
    image: python:3.7
    script:
        -   apt update
        -   apt install --yes --no-install-recommends gcc portaudio19-dev
        -   python3.7 -m venv venv
        -   venv/bin/python -m pip install --upgrade tox wheel pip
        -   venv/bin/python -m tox -e py37
    stage: test

test-py38:
    image: python:3.8
    script:
        -   apt update
        -   apt install --yes --no-install-recommends gcc portaudio19-dev
        -   python3.8 -m venv venv
        -   venv/bin/python -m pip install --upgrade tox wheel pip
        -   venv/bin/python -m tox -e py38
    stage: test

test-py39:
    image: python:3.9
    script:
        -   apt update
        -   apt install --yes --no-install-recommends gcc portaudio19-dev
        -   python3.9 -m venv venv
        -   venv/bin/python -m pip install --upgrade tox wheel pip
        -   venv/bin/python -m tox -e py39
    stage: test

test-py310:
    image: python:3.10-rc-slim-buster
    script:
        -   apt update
        -   apt install --yes --no-install-recommends
            g++
            gcc
            libavformat-dev
            libavcodec-dev
            libavdevice-dev
            libavutil-dev
            libswscale-dev
            libswresample-dev
            libavfilter-dev
            pkg-config
            portaudio19-dev
            python-dev
            cmake
            ghostscript
            git
            libffi-dev
            libfreetype6-dev
            libfribidi-dev
            libharfbuzz-dev
            libjpeg-turbo-progs
            libjpeg62-turbo-dev
            liblcms2-dev
            libopenjp2-7-dev
            libtiff5-dev
            libwebp-dev
            netpbm
            python3-dev
            python3-numpy
            python3-pyqt5
            python3-scipy
            python3-setuptools
            python3-tk
            sudo
            tcl8.6-dev
            tk8.6-dev
            virtualenv
            wget
            xvfb
            zlib1g-dev
        -   python3.10 -m venv venv
        -   venv/bin/python -m pip install --upgrade pip setuptools tox wheel
        -   venv/bin/python -m tox -e py310
    stage: test
