stages:
    -   lint
    -   test

flake8:
    image: python:3.9.5-slim-buster
    cache: {}
    script:
        -   python3.9 -m venv venv
        -   venv/bin/python -m pip install --upgrade -r requirements.d/venv.txt
        -   venv/bin/python -m tox -e flake8
    stage: lint

test-py36:
    image: python:3.6
    script:
        -   apt update
        -   apt install --yes --no-install-recommends
            gcc
            libgl1-mesa-glx
            portaudio19-dev
            xvfb
        -   python3.6 -m venv venv
        -   venv/bin/python -m pip install --upgrade -r requirements.d/venv.txt
        -   venv/bin/python -m tox -e py36
    stage: test

test-py37:
    image: python:3.7
    script:
        -   apt update
        -   apt install --yes --no-install-recommends
            gcc
            libgl1-mesa-glx
            portaudio19-dev
            xvfb
        -   python3.7 -m venv venv
        -   venv/bin/python -m pip install --upgrade -r requirements.d/venv.txt
        -   venv/bin/python -m tox -e py37
    stage: test

test-py38:
    image: python:3.8
    script:
        -   apt update
        -   apt install --yes --no-install-recommends
            gcc
            libgl1-mesa-glx
            portaudio19-dev
            xvfb
        -   python3.8 -m venv venv
        -   venv/bin/python -m pip install --upgrade -r requirements.d/venv.txt
        -   venv/bin/python -m tox -e py38
    stage: test

test-py39:
    image: python:3.9
    script:
        -   apt update
        -   apt install --yes --no-install-recommends
            gcc
            libgl1-mesa-glx
            portaudio19-dev
            xvfb
            v4l2loopback-dkms
        -   modprobe v4l2loopback
        -   ffmpeg -re -loop 1 -i data/test.png -filter:v format=yuv422p -r 30 -f v4l2 /dev/video2 &
        -   python3.9 -m venv venv
        -   venv/bin/python -m pip install --upgrade -r requirements.d/venv.txt
        -   venv/bin/python -m tox -e py39
    stage: test
